// GENERATED FILE — do not edit by hand.
// Regenerate with: node scripts/build-world-mask.mjs
//
// A 180×90 equirectangular land/ocean bitmap derived from Natural Earth
// 110m data (via world-atlas), packed 8 cells per byte and base64 encoded.
// 4852 of 16200 cells are land.

export const GRID_W = 180;
export const GRID_H = 90;
export const LAT_MAX = 84;
export const LAT_MIN = -60;

const PACKED = "AAAAAAAABAAL/AAAAAAAAAAAAAAAAAAAAAAAAP/x///vAAAAAAAAAAAAAAAAAAAAAAA9/v///4AAPwAAAADwAAAAAAAAAAAAdf9////wAA4AAAAAAOAAAAAAAAAABwBn4f///wAAAAAAEAAPAAAAAAAAAAAfivwAf//wAAAAADgAP/4AHYAAAAAADwC6oAP//wAAAAAGAD//+ADAAAAAAAHfzH+AP//AAAAAAMDd///8D4AAAH8AAD4z/wH/+AAAA8AAHf//////wAAf////AdjwD/+AAAP/gA7f////////4P//////k8H/gAAAf/6//f////////e//////+B0D+A+AA+eP///////////AD/////5Q4D8AcAB9/f//////////+Af/////wkYB4AAAH5////////////9Af9////gHgAQAAAH5///////////HwAHgP///gHkAAAAAH4//////////CMAABQB///wD+AAAAGAw/////////8A8AACAA///8D/AAAAECh/////////4A4AAAAAf///v/gAAALCP/////////wAwAAAAAf///n/wAAAbv///////////AgAAAAAP/////gAAAD///////////9AgAAAAAD////yQAAAA///////////9AAAAAAAB////48AAAD///////////8AAAAAAAD/////AAAAB//7fn//////4AAAAAAAD////+AAAAB/fweP//////wAAAAAAAD////gAAAAfxvwPP//////jgAAAAAAD////gAAAAPizzHH/////+CAAAAAAAD///+AAAAAfCCf/n/////cCAAAAAAAD///8AAAAAfABf/H////+MCAAAAAAAB///8AAAAAGOQP///////mMAAAAAAAA///8AAAAAH+Ai///////G8AAAAAAAAf//4AAAAAP+AA///////BgAAAAAAAAP//wAAAAAf/zB///////hAAAAAAAAAL//gAAAAAf/7////////gAAAAAAAAAD/AQAAAAAf////f/////gAAAAAAAAAF+AQAAAAB///+/v/////AAAAAAAAAAB+AQAAAAB///+/x/////AAAAAAAAAAA+AAAAAAD////f+D///+gAAAAAAAAAAeAYAAAAD////P/B/7/4AAAAAAAAAAAeGEAAAAD////P+B/z+AAAAAAAAAAAAPEAgAAAD////n+A/B+gAAAAAAAAAAAH8AAAAAD////n8AfB+AgAAAAAAAAAABcAAAAAD////3wAcBfAgAAAAAAAAAAAPAAAAAH/////gAcAfggAAAAAAAAAAADAAAAAD////6AAcAfggAAAAAAAAAAABBQAAAD////8wAMATAYAAAAAAAAAAAAj+AAAB/////gAIASAQAAAAAAAAAAAAX/AAAB/////gACAQAYAAAAAAAAAAAAH/gAAA/////gACAICIAAAAAAAAAAAAH/8AAAIH///AAAAsGAAAAAAAAAAAAAH/+AAAAB//+AAAAUGAAAAAAAAAAAAAH/+AAAAB//8AAAAYeAAAAAAAAAAAAAP/+AAAAB//4AAAAMeAAAAAAAAAAAAAP//wAAAB//4AAAAMcggAAAAAAAAAAAP//8AAAB//wAAAAGFm+AAAAAAAAAAAf//+AAAA//wAAAACAQPgAAAAAAAAAAP///gAAA//gAAAABAAHwAAAAAAAAAAP///gAAAf/wAAAAAYAHQQAAAAAAAAAH///AAAAf/wAAAAAAAAIAAAAAAAAAAH//+AAAAf/wAAAAAAAAAAAAAAAAAAAD//+AAAAf/wgAAAAABxAAAAAAAAAAAD//+AAAA//wgAAAAAFxAAAAAAAAAAAB//+AAAA//xgAAAAAP5gAAAAAAAAAAA//8AAAA//jgAAAAAf/gAAAAAAAAAAAf/8AAAA//DgAAAAAf/gAAAAAAAAAAAf/8AAAAf+DAAAAAD//wCAAAAAAAAAAf/4AAAAf/DAAAAAH//4AAAAAAAAAAAf/gAAAAf/DAAAAAH//8AAAAAAAAAAAf/AAAAAf8AAAAAAH//8AAAAAAAAAAAf/AAAAAP8AAAAAAH//+AAAAAAAAAAA/+AAAAAP8AAAAAAH//+AAAAAAAAAAA/+AAAAAH4AAAAAAD//+AAAAAAAAAAA/8AAAAAH4AAAAAAD8/8AAAAAAAAAAA/4AAAAAHgAAAAAADwf8AAAAAAAAAAA/gAAAAAAAAAAAAAAAP4AAAAAAAAAAB/wAAAAAAAAAAAAAAAD4AEAAAAAAAAB/gAAAAAAAAAAAAAAABwAGAAAAAAAAB+AAAAAAAAAAAAAAAAAAAEAAAAAAAAB4AAAAAAAAAAAAAAAAAQAIAAAAAAAAA8AAAAAAAAAAAAAAAAAQAQAAAAAAAAB4AAAAAAAAAAAAAAAAAAAwAAAAAAAADwAAAAAAAAAAAAAAAAAAAgAAAAAAAAD4AAAAAAAAAAAAAAAAAAAAAAAAAAAADwAAAAAAAAAACAAAAAAAAAAAAAAAAADwAAAAAAAAAAAAAAAAAAAAAAAAAAAABwAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";

let cache: Uint8Array | null = null;

/** Decoded land mask, one byte per cell (1 = land). Decoded once per process. */
export function landMask(): Uint8Array {
  if (cache) return cache;

  const binary = typeof atob === "function"
    ? atob(PACKED)
    : Buffer.from(PACKED, "base64").toString("binary");

  const out = new Uint8Array(GRID_W * GRID_H);
  for (let i = 0; i < out.length; i++) {
    out[i] = (binary.charCodeAt(i >> 3) >> (7 - (i & 7))) & 1;
  }
  cache = out;
  return out;
}

/**
 * Project lon/lat to fractional grid coordinates, so a visitor pin lands in the
 * same space as the dots. Returns null for latitudes outside the drawn band.
 */
export function project(latitude: number, longitude: number) {
  if (latitude > LAT_MAX || latitude < LAT_MIN) return null;
  return {
    x: ((longitude + 180) / 360) * GRID_W,
    y: ((LAT_MAX - latitude) / (LAT_MAX - LAT_MIN)) * GRID_H,
  };
}
