-- Event waitlist — the RSVP list behind /waitlist.
--
-- ===========================================================================
-- WHY A TABLE OF ITS OWN, AND NOT `customers`
-- ===========================================================================
-- The newsletter sign-up in the footer writes to `customers`, because that is
-- what it is: consent to be marketed to, attached to a CRM record that outlives
-- any one campaign. A waitlist is the other shape. It is bounded to a single
-- event, it carries fields the CRM has no column for (which craft someone came
-- for, their Instagram handle), and its whole job is an *ordering* — who asked
-- first. Folding that into `customers` would mean nullable campaign columns on
-- every shopper row and a queue position that means nothing to anyone who
-- bought a hoodie.
--
-- Someone on the waitlist is not thereby a newsletter subscriber. Consent to be
-- texted the address of an event you signed up for is not consent to marketing,
-- so nothing here writes to `customers` and nothing here sets
-- `accepts_marketing`. Promoting an attendee into the CRM is a deliberate act,
-- done from the admin, not a side effect of an RSVP.
--
-- ===========================================================================
-- POSITION IS A COLUMN, NOT A COUNT
-- ===========================================================================
-- The page shows each person the number they hold in line, and that number has
-- to be stable: someone who screenshots "#146" and comes back a week later must
-- still be #146, even if three people ahead of them were removed. A position
-- derived at read time (`count(*) where created_at <= mine`) is not stable
-- under deletion and needs a scan per read.
--
-- So the queue number is assigned once, by an identity column, at insert. It is
-- Postgres that hands it out, which also means two people submitting in the
-- same millisecond cannot be given the same number — the read-then-write that
-- application-side numbering would require has no safe version under
-- concurrency.
create table if not exists waitlist_entries (
  id uuid primary key default gen_random_uuid(),

  -- The number the attendee is shown and screenshots.
  --
  -- `start with 139` is a head start, not a row count: the campaign opened with
  -- a queue already quoted in that range, and restarting at 1 would have made
  -- everyone who signed up on day one look like the only person there. Use
  -- `count(*)` for "how many have actually signed up" — never `max(position)`.
  --
  -- `by default` rather than `always` so a migration or an import can carry its
  -- own numbers in; ordinary inserts leave it to the sequence.
  position bigint generated by default as identity (start with 139) not null
    constraint waitlist_entries_position_key unique,

  -- Stored lowercased and trimmed by the action, so this unique constraint is
  -- the real one-row-per-person rule. Re-submitting the same address updates
  -- the row in place and keeps the original `position` — the alternative, a
  -- second row, would quietly demote someone for correcting their phone number.
  email text not null constraint waitlist_entries_email_key unique,

  -- Required: the address goes out by text the night before, which is the whole
  -- reason it is collected. Free-form on purpose — the action normalises far
  -- enough to reject a non-number and no further, because a stricter shape
  -- would reject legitimate international formats.
  phone text not null,

  -- Optional, and stored without the leading '@'.
  instagram text not null default '',

  -- Which of the four things they came to make. Constrained rather than an
  -- enum: this is campaign copy, and a new craft next season should be a
  -- one-line change here, not a new type in the schema that can never be
  -- dropped cleanly.
  craft text not null default 'fan'
    constraint waitlist_entries_craft_check
    check (craft in ('fan', 'lantern', 'keychain', 'polaroid')),

  -- Admin triage.
  --   waiting   — signed up, nothing sent yet
  --   invited   — offered a seat
  --   confirmed — coming
  --   declined  — offered and passed, or removed
  status text not null default 'waiting'
    constraint waitlist_entries_status_check
    check (status in ('waiting', 'invited', 'confirmed', 'declined')),

  -- Staff-only, never shown to the attendee.
  notes text not null default '',

  -- Attribution, for judging whether a campaign was worth running. Nullable and
  -- unvalidated: it is a hint, not a fact.
  source text not null default '',

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- The admin list is "newest first"; the queue view is "by position". Both are
-- covered without a scan.
create index if not exists waitlist_entries_created_idx
  on waitlist_entries (created_at desc);
create index if not exists waitlist_entries_status_idx
  on waitlist_entries (status, position);

-- `set_updated_at()` is defined in 0001_init.sql.
drop trigger if exists waitlist_entries_updated_at on waitlist_entries;
create trigger waitlist_entries_updated_at
  before update on waitlist_entries
  for each row execute function set_updated_at();

-- ---------------------------------------------------------------------------
-- RLS — staff read, service-role write, nothing at all for anon.
-- ---------------------------------------------------------------------------
-- Same posture as `analytics_*` and `customers`: the sign-up form is public and
-- unauthenticated, so the insert is done with the service-role key from a
-- Server Action, where the validation lives. A public insert policy would let
-- anyone write arbitrary rows into the list — and, worse, an anon *select*
-- policy would publish every attendee's email and phone number to anyone who
-- opened the network tab.
--
-- Gated on `public.is_staff()` (0009) rather than the bare `to authenticated`
-- that `analytics_*` still uses, and the difference is load-bearing here: since
-- customer accounts landed, every *shopper* who logs in is `authenticated` too.
-- `using (true)` would hand the entire attendee list — names, emails, phone
-- numbers — to anyone who registered on the storefront.
alter table waitlist_entries enable row level security;

grant select, update, delete on waitlist_entries to authenticated;

create policy waitlist_entries_staff_read on waitlist_entries
  for select to authenticated using (public.is_staff());

create policy waitlist_entries_staff_write on waitlist_entries
  for update to authenticated using (public.is_staff()) with check (public.is_staff());

create policy waitlist_entries_staff_delete on waitlist_entries
  for delete to authenticated using (public.is_staff());
